[package]
name = "mongo"
version = "0.1.0"
authors = ["youshy <devilyoushy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
# rocket_codegen = "0.3.17"
